
'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { FancyAccordionButton } from './FancyAccordionButton';
import { Download, Loader2, Image as ImageIcon, Wand2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Label } from '@/components/ui/label';
import { generateImage } from '@/ai/flows/image-generator';
import Image from 'next/image';

export function ImageGenerator() {
  const [prompt, setPrompt] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      toast({
        variant: 'destructive',
        title: 'Prompt is required',
        description: 'Please enter a description for the image you want to create.',
      });
      return;
    }
    setIsLoading(true);
    setImageUrl('');
    try {
      const result = await generateImage({ prompt });
      setImageUrl(result.imageUrl);
    } catch (error) {
      console.error(error);
      toast({
        variant: 'destructive',
        title: 'An error occurred',
        description: 'Failed to generate image. The model may be rate-limited or the prompt was blocked for safety. Please try again later or with a different prompt.',
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownload = async () => {
    if (!imageUrl) return;
    try {
      const link = document.createElement('a');
      link.href = imageUrl;
      link.download = `kimi-pk-generated-image.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
        toast({
            variant: 'destructive',
            title: 'Download Failed',
            description: 'Could not download the image.',
        });
    }
  };

  return (
    <div className="w-full">
      <Card className="bg-card/50 dark:bg-card/20 backdrop-blur-sm border-border/50">
        <CardHeader className="items-center text-center">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary mb-4">
                <ImageIcon className="h-6 w-6 text-primary-foreground" />
            </div>
            <CardTitle className="text-3xl font-bold font-headline">AI Image Creator</CardTitle>
            <p className="text-muted-foreground">Generate unique images from text descriptions.</p>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="prompt-input">Enter your image prompt</Label>
            <Textarea
              id="prompt-input"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g., 'a cinematic shot of a majestic dragon soaring over a mystical forest at dawn'"
              rows={3}
            />
          </div>

          <Button onClick={handleGenerate} disabled={isLoading} className="w-full" size="lg">
            {isLoading ? <Loader2 className="mr-2 h-5 w-5 animate-spin" /> : <Wand2 className="mr-2 h-5 w-5" />}
            {isLoading ? 'Generating...' : 'Generate Image'}
          </Button>

          {(imageUrl || isLoading) && (
            <div className="space-y-4 pt-4 border-t flex flex-col items-center justify-center">
              <h3 className="text-lg font-semibold">Generated Image</h3>
              {isLoading ? (
                <div className="flex items-center justify-center p-8">
                  <Loader2 className="h-12 w-12 animate-spin text-primary" />
                </div>
              ) : (
                imageUrl && (
                    <div className="p-2 bg-white rounded-md border inline-block aspect-square relative w-full max-w-sm">
                        <Image
                            src={imageUrl}
                            alt="Generated by AI"
                            fill
                            className="object-contain"
                            sizes="(max-width: 768px) 100vw, 33vw"
                        />
                    </div>
                )
              )}
              {!isLoading && imageUrl && (
                 <Button onClick={handleDownload} variant="outline">
                    <Download className="mr-2 h-4 w-4" /> Download Image
                </Button>
              )}
            </div>
          )}
        </CardContent>
      </Card>
      
      <div className="mt-6">
        <Accordion type="single" collapsible>
            <AccordionItem value="guide" className="border-none">
                <AccordionTrigger className="p-0 hover:no-underline [&>svg]:hidden">
                    <FancyAccordionButton />
                </AccordionTrigger>
                <AccordionContent className="mt-2 p-6 rounded-lg bg-card/50 dark:bg-card/20 prose dark:prose-invert max-w-none text-sm">
                    <p>This tool uses AI to create a unique image based on a text description you provide.</p>
                    <ol>
                        <li>Write a detailed description of the image you want in the prompt box. Be creative! (e.g., "a futuristic cityscape in Pakistan at sunset, with flying rickshaws").</li>
                        <li>Click the "Generate Image" button. Please be patient, as this can take several seconds.</li>
                        <li>Your unique, AI-generated image will appear below.</li>
                        <li>Use the "Download Image" button to save it to your device.</li>
                    </ol>
                    <p>It's perfect for creating custom graphics, illustrations for your blog, social media posts, or just for fun. The AI is configured to avoid creating unsafe or inappropriate content.</p>
                </AccordionContent>
            </AccordionItem>
        </Accordion>
      </div>

    </div>
  );
}
